// GENERATED by tools/digit-atlas/gen_damage_digits.py -- do not edit; re-run the script.
// The glyph table for `/ui/damage_digits.png` (design/10 "Damage numbers"): ten digits and the
// marks "+" and "!" in Rubik Bold (OFL-1.1), white fill under a 5 px dark
// outline, one shared cell.
// Font SHA-256: b1c36dfcbc5fe5011c552c76725c84d989a71d56440e8bfbfa0cb68b593dbad6
// Sheet SHA-256: b515aecd71d7c161d8f45c93f55d4ad4c939e034d5aa09b54cb31e4a0a8cb326

/** The atlas file, a key-for-key entry in `UI_ASSETS`. */
export const DAMAGE_DIGITS_PATH = '/ui/damage_digits.png';

export const DAMAGE_DIGIT_ATLAS = {
  /** One digit's cell, atlas px — every digit has the same size and baseline. */
  cellW: 52,
  cellH: 54,
  /** Each glyph's cell left edge: indices 0-9 are the digits themselves, then `plus` and `bang`. */
  frameX: [4, 64, 124, 184, 244, 304, 364, 424, 484, 544, 604, 664] as readonly number[],
  /** The heal prefix "+". */
  plus: 10,
  /** The crit suffix "!". */
  bang: 11,
  /** Every cell's top edge. */
  frameY: 4,
  /** Origin-to-origin distance between two digits of one number, atlas px. */
  advance: 45,
  /** The "!" glyph's own share of that distance, atlas px — it is much narrower than a digit. */
  bangAdvance: 21,
} as const;
