// GENERATED by tools/digit-atlas/gen_damage_digits.py -- do not edit; re-run the script.
// The glyph table for `/ui/damage_digits.png` (design/10 "Damage numbers"): ten digits of
// Rubik Bold (OFL-1.1), white fill under a 5 px dark outline, one shared cell.
// Font SHA-256: b1c36dfcbc5fe5011c552c76725c84d989a71d56440e8bfbfa0cb68b593dbad6
// Sheet SHA-256: 1bd505273e58124b57aff6d7ffbd3ebb5a2902c8c56170770dad1ae4338aabcc

/** The atlas file, a key-for-key entry in `UI_ASSETS`. */
export const DAMAGE_DIGITS_PATH = '/ui/damage_digits.png';

export const DAMAGE_DIGIT_ATLAS = {
  /** One digit's cell, atlas px — every digit has the same size and baseline. */
  cellW: 52,
  cellH: 54,
  /** Each digit's cell left edge, indexed by the digit itself. */
  frameX: [4, 64, 124, 184, 244, 304, 364, 424, 484, 544] as readonly number[],
  /** Every cell's top edge. */
  frameY: 4,
  /** Origin-to-origin distance between two digits of one number, atlas px. */
  advance: 45,
} as const;
